import { spawnSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import path from 'node:path';

type Check = {
  name: string;
  passed: boolean;
  detail?: string;
};

const ROOT = process.cwd();
const NPM = process.platform === 'win32' ? 'npm.cmd' : 'npm';
const RUNTIME_DIRS = ['app', 'components', 'lib', 'store', 'scripts'];
const ROUTE_FILES = [
  'app/page.tsx',
  'app/feed/page.tsx',
  'app/build/page.tsx',
  'app/wardrobe/page.tsx',
  'app/discover/page.tsx',
  'app/profile/page.tsx',
  'app/saved/page.tsx',
  'app/try-on/page.tsx',
  'app/checkout/page.tsx',
];
const REQUIRED_SCRIPTS = ['catalog:health', 'catalog:test-generator', 'import:catalog', 'qa'];
function isQaSelf(file: string): boolean {
  const normalized = file.replace(/\\/g, '/');
  return normalized.endsWith('scripts/qa-check.ts');
}
function isQualityLib(file: string): boolean {
  const normalized = file.replace(/\\/g, '/');
  return normalized.endsWith('lib/product-image-quality.ts');
}
function isQuarantinedMockLib(file: string): boolean {
  const normalized = file.replace(/\\/g, '/');
  // lib/mock-products.ts and lib/brand-catalog.ts are isolated dev/test fixtures
  // verified not imported by app/components/store (separate QA check enforces this).
  return normalized.endsWith('lib/mock-products.ts') || normalized.endsWith('lib/brand-catalog.ts');
}
const DANGEROUS_PATTERNS: Array<{ label: string; pattern: RegExp; allow?: (file: string, line: string) => boolean }> = [
  { label: 'broken template string', pattern: /return\s+\$\$\{/ },
  { label: 'invalid currentItems spread', pattern: /\.\.\.currentItems:\s*lockedItems/ },
  {
    label: 'fake product label',
    pattern: /\bProduct A\b|\bSample Item\b|\bPlaceholder Top\b|\bPlaceholder Shoes\b|placeholder product/i,
    allow: (file) => isQaSelf(file) || isQualityLib(file),
  },
  {
    label: 'placeholder SearchAPI key in runtime',
    pattern: /your_key_here/,
    allow: (file) => file.endsWith('.env.example') || isQaSelf(file),
  },
  { label: 'black letter product fallback', pattern: /bg-black\s+text-white/ },
  {
    label: 'fallback initial variable',
    pattern: /fallbackInitial/,
    allow: (file) => isQaSelf(file),
  },
  {
    label: 'data:image/svg used as runtime image URL',
    pattern: /data:image\/svg/,
    // Allow inside quarantined mock libs (verified not imported by runtime).
    allow: (file) => isQaSelf(file) || isQuarantinedMockLib(file),
  },
  {
    label: 'product fallback initial via charAt(0)',
    pattern: /\.charAt\(0\)/,
    // Only flag if the same line references brand/name/fallback/initial (product-letter-fallback context).
    allow: (file, line) => isQaSelf(file) || !/(brand|name|fallback|initial|letter|abbrev)/i.test(line),
  },
  {
    label: 'naked toLocaleString without locale (hydration risk)',
    pattern: /\.toLocaleString\(\s*\)/,
    allow: (file) => isQaSelf(file),
  },
  {
    label: 'mock-products imported into runtime',
    pattern: /from\s+['"](\.\.\/)*lib\/mock-products['"]/,
    allow: (file) => isQaSelf(file),
  },
  {
    label: 'fake social stat phrase',
    pattern: /\bfollowers\b|\bfollowing\b|fake likes|trending with friends/i,
    allow: (file) => isQaSelf(file),
  },
  {
    label: 'fake AI backend claim',
    pattern: /generated by AI|thinking with GPT|GPT thinking/i,
    allow: (file) => isQaSelf(file),
  },
];

function run(command: string, args: string[]): Check {
  const result = spawnSync(command, args, {
    cwd: ROOT,
    encoding: 'utf8',
    shell: true,
    stdio: 'pipe',
  });
  const output = `${result.stdout || ''}${result.stderr || ''}${result.error ? `\n${result.error.message}` : ''}`.trim();
  return {
    name: `${command} ${args.join(' ')}`,
    passed: result.status === 0,
    detail: output.split(/\r?\n/).slice(-8).join('\n'),
  };
}

function walk(dir: string): string[] {
  const absolute = path.join(ROOT, dir);
  if (!existsSync(absolute)) return [];
  return readdirSync(absolute).flatMap((entry) => {
    const file = path.join(absolute, entry);
    const stat = statSync(file);
    if (stat.isDirectory()) {
      if (['node_modules', '.next', '.git'].includes(entry)) return [];
      return walk(path.relative(ROOT, file));
    }
    if (!/\.(ts|tsx|js|jsx|mts|mjs)$/.test(file)) return [];
    return [file];
  });
}

function scanDangerousStrings(): Check {
  const hits: string[] = [];
  for (const file of RUNTIME_DIRS.flatMap(walk)) {
    const relative = path.relative(ROOT, file);
    const lines = readFileSync(file, 'utf8').split(/\r?\n/);
    lines.forEach((line, index) => {
      for (const rule of DANGEROUS_PATTERNS) {
        if (!rule.pattern.test(line)) continue;
        if (rule.allow?.(relative, line)) continue;
        hits.push(`${relative}:${index + 1} ${rule.label}`);
      }
    });
  }

  return {
    name: 'dangerous runtime string scan',
    passed: hits.length === 0,
    detail: hits.slice(0, 20).join('\n') || 'no dangerous runtime strings found',
  };
}

function checkRouteFiles(): Check {
  const missing = ROUTE_FILES.filter((file) => !existsSync(path.join(ROOT, file)));
  return {
    name: 'route file existence',
    passed: missing.length === 0,
    detail: missing.length ? `Missing: ${missing.join(', ')}` : `${ROUTE_FILES.length} route files present`,
  };
}

function checkPackageScripts(): Check {
  const packageJson = JSON.parse(readFileSync(path.join(ROOT, 'package.json'), 'utf8')) as { scripts?: Record<string, string> };
  const missing = REQUIRED_SCRIPTS.filter((script) => !packageJson.scripts?.[script]);
  return {
    name: 'package script existence',
    passed: missing.length === 0,
    detail: missing.length ? `Missing scripts: ${missing.join(', ')}` : `${REQUIRED_SCRIPTS.join(', ')} present`,
  };
}

function checkRuvectorNotTracked(): Check {
  const result = spawnSync('git', ['ls-files', 'ruvector.db'], {
    cwd: ROOT,
    encoding: 'utf8',
    shell: true,
    stdio: 'pipe',
  });
  const tracked = (result.stdout || '').trim();
  return {
    name: 'ruvector database not tracked',
    passed: !tracked,
    detail: tracked ? `Tracked file: ${tracked}` : 'ruvector.db is not tracked',
  };
}

function checkMockIsolation(): Check {
  // Quarantined fixtures must NOT be imported by app/components/store runtime.
  const QUARANTINED_LIBS = ['lib/mock-products', 'lib/brand-catalog', 'lib/expansion-catalog'];
  const RUNTIME_SCOPES = ['app', 'components', 'store'];
  const hits: string[] = [];
  for (const file of RUNTIME_SCOPES.flatMap(walk)) {
    const relative = path.relative(ROOT, file).replace(/\\/g, '/');
    const content = readFileSync(file, 'utf8');
    for (const lib of QUARANTINED_LIBS) {
      const importRegex = new RegExp(`from\\s+['"](\\.\\.?/)+${lib.replace('/', '\\/')}['"]`);
      if (importRegex.test(content)) {
        hits.push(`${relative} imports quarantined ${lib}`);
      }
    }
  }
  return {
    name: 'mock/brand catalog isolation',
    passed: hits.length === 0,
    detail: hits.length ? hits.join('\n') : 'mock-products, brand-catalog, expansion-catalog not imported by app/components/store',
  };
}

async function main() {
  const checks: Check[] = [
    run(NPM, ['run', 'typecheck']),
    run(NPM, ['run', 'catalog:health']),
    run(NPM, ['run', 'catalog:test-generator']),
    run('npx', ['jiti', 'scripts/check-outfit-completeness.ts']),
    run('npx', ['jiti', 'scripts/check-feed-seed-uniqueness.ts']),
    run('npx', ['jiti', 'scripts/check-legacy-vibe-safety.ts']),
    scanDangerousStrings(),
    checkMockIsolation(),
    checkRouteFiles(),
    checkPackageScripts(),
    checkRuvectorNotTracked(),
  ];

  for (const check of checks) {
    console.log(`${check.passed ? 'PASS' : 'FAIL'} ${check.name}`);
    if (check.detail) console.log(check.detail);
    console.log('');
  }

  const failed = checks.filter((check) => !check.passed);
  console.log(`QA summary: ${checks.length - failed.length}/${checks.length} checks passed.`);
  if (failed.length) process.exitCode = 1;
}

main().catch((error) => {
  console.error('QA runner failed:', error);
  process.exitCode = 1;
});
